#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADM.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ADMDB")]
	public partial class ADMDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCube_Detail(Cube_Detail instance);
    partial void UpdateCube_Detail(Cube_Detail instance);
    partial void DeleteCube_Detail(Cube_Detail instance);
    partial void InsertCube_Receiving(Cube_Receiving instance);
    partial void UpdateCube_Receiving(Cube_Receiving instance);
    partial void DeleteCube_Receiving(Cube_Receiving instance);
    #endregion
		
		public ADMDBDataContext() : 
				base(global::ADM.Data.Properties.Settings.Default.ADMDBConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public ADMDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ADMDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ADMDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ADMDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Cube_Detail> Cube_Details
		{
			get
			{
				return this.GetTable<Cube_Detail>();
			}
		}
		
		public System.Data.Linq.Table<Cube_Receiving> Cube_Receivings
		{
			get
			{
				return this.GetTable<Cube_Receiving>();
			}
		}
		
		public System.Data.Linq.Table<vCubeTestAll> vCubeTestAlls
		{
			get
			{
				return this.GetTable<vCubeTestAll>();
			}
		}
		
		public System.Data.Linq.Table<vCubeTestToday> vCubeTestTodays
		{
			get
			{
				return this.GetTable<vCubeTestToday>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateCubeLoad")]
		public ISingleResult<UpdateCubeLoadResult> UpdateCubeLoad([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CubeID", DbType="Int")] System.Nullable<int> cubeID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SampleMass", DbType="Real")] System.Nullable<float> sampleMass, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaxLoad", DbType="Real")] System.Nullable<float> maxLoad)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cubeID, sampleMass, maxLoad);
			return ((ISingleResult<UpdateCubeLoadResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Cube Details]")]
	public partial class Cube_Detail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CubeID;
		
		private string _JobRef;
		
		private System.Nullable<int> _Set_No;
		
		private string _SpecimenRef;
		
		private string _Size;
		
		private System.Nullable<System.DateTime> _DateCast;
		
		private System.Nullable<int> _Age;
		
		private System.Nullable<System.DateTime> _DateTest;
		
		private string _Grade;
		
		private System.Nullable<float> _SampleMass;
		
		private System.Nullable<float> _MaxLoad;
		
		private EntityRef<Cube_Receiving> _Cube_Receiving;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCubeIDChanging(int value);
    partial void OnCubeIDChanged();
    partial void OnJobRefChanging(string value);
    partial void OnJobRefChanged();
    partial void OnSet_NoChanging(System.Nullable<int> value);
    partial void OnSet_NoChanged();
    partial void OnSpecimenRefChanging(string value);
    partial void OnSpecimenRefChanged();
    partial void OnSizeChanging(string value);
    partial void OnSizeChanged();
    partial void OnDateCastChanging(System.Nullable<System.DateTime> value);
    partial void OnDateCastChanged();
    partial void OnAgeChanging(System.Nullable<int> value);
    partial void OnAgeChanged();
    partial void OnDateTestChanging(System.Nullable<System.DateTime> value);
    partial void OnDateTestChanged();
    partial void OnGradeChanging(string value);
    partial void OnGradeChanged();
    partial void OnSampleMassChanging(System.Nullable<float> value);
    partial void OnSampleMassChanged();
    partial void OnMaxLoadChanging(System.Nullable<float> value);
    partial void OnMaxLoadChanged();
    #endregion
		
		public Cube_Detail()
		{
			this._Cube_Receiving = default(EntityRef<Cube_Receiving>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CubeID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CubeID
		{
			get
			{
				return this._CubeID;
			}
			set
			{
				if ((this._CubeID != value))
				{
					this.OnCubeIDChanging(value);
					this.SendPropertyChanging();
					this._CubeID = value;
					this.SendPropertyChanged("CubeID");
					this.OnCubeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobRef", DbType="NVarChar(255)")]
		public string JobRef
		{
			get
			{
				return this._JobRef;
			}
			set
			{
				if ((this._JobRef != value))
				{
					if (this._Cube_Receiving.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnJobRefChanging(value);
					this.SendPropertyChanging();
					this._JobRef = value;
					this.SendPropertyChanged("JobRef");
					this.OnJobRefChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Set No]", Storage="_Set_No", DbType="Int")]
		public System.Nullable<int> Set_No
		{
			get
			{
				return this._Set_No;
			}
			set
			{
				if ((this._Set_No != value))
				{
					this.OnSet_NoChanging(value);
					this.SendPropertyChanging();
					this._Set_No = value;
					this.SendPropertyChanged("Set_No");
					this.OnSet_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpecimenRef", DbType="NVarChar(255)")]
		public string SpecimenRef
		{
			get
			{
				return this._SpecimenRef;
			}
			set
			{
				if ((this._SpecimenRef != value))
				{
					this.OnSpecimenRefChanging(value);
					this.SendPropertyChanging();
					this._SpecimenRef = value;
					this.SendPropertyChanged("SpecimenRef");
					this.OnSpecimenRefChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size", DbType="NVarChar(255)")]
		public string Size
		{
			get
			{
				return this._Size;
			}
			set
			{
				if ((this._Size != value))
				{
					this.OnSizeChanging(value);
					this.SendPropertyChanging();
					this._Size = value;
					this.SendPropertyChanged("Size");
					this.OnSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCast", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateCast
		{
			get
			{
				return this._DateCast;
			}
			set
			{
				if ((this._DateCast != value))
				{
					this.OnDateCastChanging(value);
					this.SendPropertyChanging();
					this._DateCast = value;
					this.SendPropertyChanged("DateCast");
					this.OnDateCastChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Int")]
		public System.Nullable<int> Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this.OnAgeChanging(value);
					this.SendPropertyChanging();
					this._Age = value;
					this.SendPropertyChanged("Age");
					this.OnAgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTest", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateTest
		{
			get
			{
				return this._DateTest;
			}
			set
			{
				if ((this._DateTest != value))
				{
					this.OnDateTestChanging(value);
					this.SendPropertyChanging();
					this._DateTest = value;
					this.SendPropertyChanged("DateTest");
					this.OnDateTestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grade", DbType="NVarChar(255)")]
		public string Grade
		{
			get
			{
				return this._Grade;
			}
			set
			{
				if ((this._Grade != value))
				{
					this.OnGradeChanging(value);
					this.SendPropertyChanging();
					this._Grade = value;
					this.SendPropertyChanged("Grade");
					this.OnGradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SampleMass", DbType="Real")]
		public System.Nullable<float> SampleMass
		{
			get
			{
				return this._SampleMass;
			}
			set
			{
				if ((this._SampleMass != value))
				{
					this.OnSampleMassChanging(value);
					this.SendPropertyChanging();
					this._SampleMass = value;
					this.SendPropertyChanged("SampleMass");
					this.OnSampleMassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxLoad", DbType="Real")]
		public System.Nullable<float> MaxLoad
		{
			get
			{
				return this._MaxLoad;
			}
			set
			{
				if ((this._MaxLoad != value))
				{
					this.OnMaxLoadChanging(value);
					this.SendPropertyChanging();
					this._MaxLoad = value;
					this.SendPropertyChanged("MaxLoad");
					this.OnMaxLoadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cube_Receiving_Cube_Detail", Storage="_Cube_Receiving", ThisKey="JobRef", OtherKey="JobRef", IsForeignKey=true)]
		public Cube_Receiving Cube_Receiving
		{
			get
			{
				return this._Cube_Receiving.Entity;
			}
			set
			{
				Cube_Receiving previousValue = this._Cube_Receiving.Entity;
				if (((previousValue != value) 
							|| (this._Cube_Receiving.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cube_Receiving.Entity = null;
						previousValue.Cube_Details.Remove(this);
					}
					this._Cube_Receiving.Entity = value;
					if ((value != null))
					{
						value.Cube_Details.Add(this);
						this._JobRef = value.JobRef;
					}
					else
					{
						this._JobRef = default(string);
					}
					this.SendPropertyChanged("Cube_Receiving");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Cube Receiving]")]
	public partial class Cube_Receiving : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _JobRef;
		
		private string _ProjectCode;
		
		private System.Nullable<System.DateTime> _DateReceived;
		
		private string _ClientRef;
		
		private string _Casting_Location;
		
		private string _SampleCondition;
		
		private string _TestCondition;
		
		private System.Nullable<int> _TestedBy;
		
		private System.Nullable<int> _PreparedBy;
		
		private System.Nullable<int> _ApprovedBy;
		
		private System.Nullable<System.DateTime> _DateReport;
		
		private string _Remarks;
		
		private string _InvoiceNo;
		
		private string _DateCollection;
		
		private System.Nullable<int> _Field1;
		
		private EntitySet<Cube_Detail> _Cube_Details;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnJobRefChanging(string value);
    partial void OnJobRefChanged();
    partial void OnProjectCodeChanging(string value);
    partial void OnProjectCodeChanged();
    partial void OnDateReceivedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateReceivedChanged();
    partial void OnClientRefChanging(string value);
    partial void OnClientRefChanged();
    partial void OnCasting_LocationChanging(string value);
    partial void OnCasting_LocationChanged();
    partial void OnSampleConditionChanging(string value);
    partial void OnSampleConditionChanged();
    partial void OnTestConditionChanging(string value);
    partial void OnTestConditionChanged();
    partial void OnTestedByChanging(System.Nullable<int> value);
    partial void OnTestedByChanged();
    partial void OnPreparedByChanging(System.Nullable<int> value);
    partial void OnPreparedByChanged();
    partial void OnApprovedByChanging(System.Nullable<int> value);
    partial void OnApprovedByChanged();
    partial void OnDateReportChanging(System.Nullable<System.DateTime> value);
    partial void OnDateReportChanged();
    partial void OnRemarksChanging(string value);
    partial void OnRemarksChanged();
    partial void OnInvoiceNoChanging(string value);
    partial void OnInvoiceNoChanged();
    partial void OnDateCollectionChanging(string value);
    partial void OnDateCollectionChanged();
    partial void OnField1Changing(System.Nullable<int> value);
    partial void OnField1Changed();
    #endregion
		
		public Cube_Receiving()
		{
			this._Cube_Details = new EntitySet<Cube_Detail>(new Action<Cube_Detail>(this.attach_Cube_Details), new Action<Cube_Detail>(this.detach_Cube_Details));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobRef", DbType="NVarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string JobRef
		{
			get
			{
				return this._JobRef;
			}
			set
			{
				if ((this._JobRef != value))
				{
					this.OnJobRefChanging(value);
					this.SendPropertyChanging();
					this._JobRef = value;
					this.SendPropertyChanged("JobRef");
					this.OnJobRefChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectCode", DbType="NVarChar(255)")]
		public string ProjectCode
		{
			get
			{
				return this._ProjectCode;
			}
			set
			{
				if ((this._ProjectCode != value))
				{
					this.OnProjectCodeChanging(value);
					this.SendPropertyChanging();
					this._ProjectCode = value;
					this.SendPropertyChanged("ProjectCode");
					this.OnProjectCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateReceived", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateReceived
		{
			get
			{
				return this._DateReceived;
			}
			set
			{
				if ((this._DateReceived != value))
				{
					this.OnDateReceivedChanging(value);
					this.SendPropertyChanging();
					this._DateReceived = value;
					this.SendPropertyChanged("DateReceived");
					this.OnDateReceivedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientRef", DbType="NVarChar(255)")]
		public string ClientRef
		{
			get
			{
				return this._ClientRef;
			}
			set
			{
				if ((this._ClientRef != value))
				{
					this.OnClientRefChanging(value);
					this.SendPropertyChanging();
					this._ClientRef = value;
					this.SendPropertyChanged("ClientRef");
					this.OnClientRefChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Casting Location]", Storage="_Casting_Location", DbType="NVarChar(255)")]
		public string Casting_Location
		{
			get
			{
				return this._Casting_Location;
			}
			set
			{
				if ((this._Casting_Location != value))
				{
					this.OnCasting_LocationChanging(value);
					this.SendPropertyChanging();
					this._Casting_Location = value;
					this.SendPropertyChanged("Casting_Location");
					this.OnCasting_LocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SampleCondition", DbType="NVarChar(255)")]
		public string SampleCondition
		{
			get
			{
				return this._SampleCondition;
			}
			set
			{
				if ((this._SampleCondition != value))
				{
					this.OnSampleConditionChanging(value);
					this.SendPropertyChanging();
					this._SampleCondition = value;
					this.SendPropertyChanged("SampleCondition");
					this.OnSampleConditionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestCondition", DbType="NVarChar(255)")]
		public string TestCondition
		{
			get
			{
				return this._TestCondition;
			}
			set
			{
				if ((this._TestCondition != value))
				{
					this.OnTestConditionChanging(value);
					this.SendPropertyChanging();
					this._TestCondition = value;
					this.SendPropertyChanged("TestCondition");
					this.OnTestConditionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestedBy", DbType="Int")]
		public System.Nullable<int> TestedBy
		{
			get
			{
				return this._TestedBy;
			}
			set
			{
				if ((this._TestedBy != value))
				{
					this.OnTestedByChanging(value);
					this.SendPropertyChanging();
					this._TestedBy = value;
					this.SendPropertyChanged("TestedBy");
					this.OnTestedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreparedBy", DbType="Int")]
		public System.Nullable<int> PreparedBy
		{
			get
			{
				return this._PreparedBy;
			}
			set
			{
				if ((this._PreparedBy != value))
				{
					this.OnPreparedByChanging(value);
					this.SendPropertyChanging();
					this._PreparedBy = value;
					this.SendPropertyChanged("PreparedBy");
					this.OnPreparedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApprovedBy", DbType="Int")]
		public System.Nullable<int> ApprovedBy
		{
			get
			{
				return this._ApprovedBy;
			}
			set
			{
				if ((this._ApprovedBy != value))
				{
					this.OnApprovedByChanging(value);
					this.SendPropertyChanging();
					this._ApprovedBy = value;
					this.SendPropertyChanged("ApprovedBy");
					this.OnApprovedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateReport", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateReport
		{
			get
			{
				return this._DateReport;
			}
			set
			{
				if ((this._DateReport != value))
				{
					this.OnDateReportChanging(value);
					this.SendPropertyChanging();
					this._DateReport = value;
					this.SendPropertyChanged("DateReport");
					this.OnDateReportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="NVarChar(MAX)")]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this.OnRemarksChanging(value);
					this.SendPropertyChanging();
					this._Remarks = value;
					this.SendPropertyChanged("Remarks");
					this.OnRemarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNo", DbType="NVarChar(255)")]
		public string InvoiceNo
		{
			get
			{
				return this._InvoiceNo;
			}
			set
			{
				if ((this._InvoiceNo != value))
				{
					this.OnInvoiceNoChanging(value);
					this.SendPropertyChanging();
					this._InvoiceNo = value;
					this.SendPropertyChanged("InvoiceNo");
					this.OnInvoiceNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCollection", DbType="NVarChar(255)")]
		public string DateCollection
		{
			get
			{
				return this._DateCollection;
			}
			set
			{
				if ((this._DateCollection != value))
				{
					this.OnDateCollectionChanging(value);
					this.SendPropertyChanging();
					this._DateCollection = value;
					this.SendPropertyChanged("DateCollection");
					this.OnDateCollectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field1", DbType="Int")]
		public System.Nullable<int> Field1
		{
			get
			{
				return this._Field1;
			}
			set
			{
				if ((this._Field1 != value))
				{
					this.OnField1Changing(value);
					this.SendPropertyChanging();
					this._Field1 = value;
					this.SendPropertyChanged("Field1");
					this.OnField1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cube_Receiving_Cube_Detail", Storage="_Cube_Details", ThisKey="JobRef", OtherKey="JobRef")]
		public EntitySet<Cube_Detail> Cube_Details
		{
			get
			{
				return this._Cube_Details;
			}
			set
			{
				this._Cube_Details.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Cube_Details(Cube_Detail entity)
		{
			this.SendPropertyChanging();
			entity.Cube_Receiving = this;
		}
		
		private void detach_Cube_Details(Cube_Detail entity)
		{
			this.SendPropertyChanging();
			entity.Cube_Receiving = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vCubeTestAll")]
	public partial class vCubeTestAll
	{
		
		private string _BarCode;
		
		private string _SpecimenRef;
		
		private string _JobRef;
		
		private string _ProjectCode;
		
		private string _Company;
		
		private string _ProjectTitle;
		
		private string _Size;
		
		private System.Nullable<System.DateTime> _DateCast;
		
		private System.Nullable<int> _Age;
		
		private System.Nullable<System.DateTime> _DateTest;
		
		private string _Grade;
		
		private System.Nullable<float> _SampleMass;
		
		private System.Nullable<float> _MaxLoad;
		
		private int _CubeID;
		
		
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarCode", DbType="NVarChar(264)")]
		public string BarCode
		{
			get
			{
				return this._BarCode;
			}
			set
			{
				if ((this._BarCode != value))
				{
					this._BarCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpecimenRef", DbType="NVarChar(255)")]
		public string SpecimenRef
		{
			get
			{
				return this._SpecimenRef;
			}
			set
			{
				if ((this._SpecimenRef != value))
				{
					this._SpecimenRef = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobRef", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string JobRef
		{
			get
			{
				return this._JobRef;
			}
			set
			{
				if ((this._JobRef != value))
				{
					this._JobRef = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectCode", DbType="NVarChar(255)")]
		public string ProjectCode
		{
			get
			{
				return this._ProjectCode;
			}
			set
			{
				if ((this._ProjectCode != value))
				{
					this._ProjectCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="NVarChar(50)")]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this._Company = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectTitle", DbType="NVarChar(255)")]
		public string ProjectTitle
		{
			get
			{
				return this._ProjectTitle;
			}
			set
			{
				if ((this._ProjectTitle != value))
				{
					this._ProjectTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size", DbType="NVarChar(255)")]
		public string Size
		{
			get
			{
				return this._Size;
			}
			set
			{
				if ((this._Size != value))
				{
					this._Size = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCast", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateCast
		{
			get
			{
				return this._DateCast;
			}
			set
			{
				if ((this._DateCast != value))
				{
					this._DateCast = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Int")]
		public System.Nullable<int> Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this._Age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTest", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateTest
		{
			get
			{
				return this._DateTest;
			}
			set
			{
				if ((this._DateTest != value))
				{
					this._DateTest = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grade", DbType="NVarChar(255)")]
		public string Grade
		{
			get
			{
				return this._Grade;
			}
			set
			{
				if ((this._Grade != value))
				{
					this._Grade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SampleMass", DbType="Real")]
		public System.Nullable<float> SampleMass
		{
			get
			{
				return this._SampleMass;
			}
			set
			{
				if ((this._SampleMass != value))
				{
					this._SampleMass = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxLoad", DbType="Real")]
		public System.Nullable<float> MaxLoad
		{
			get
			{
				return this._MaxLoad;
			}
			set
			{
				if ((this._MaxLoad != value))
				{
					this._MaxLoad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CubeID", DbType="Int NOT NULL")]
		public int CubeID
		{
			get
			{
				return this._CubeID;
			}
			set
			{
				if ((this._CubeID != value))
				{
					this._CubeID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vCubeTestToday")]
	public partial class vCubeTestToday
	{
		
		private string _BarCode;
		
		private string _SpecimenRef;
		
		private string _JobRef;
		
		private string _ProjectCode;
		
		private System.Nullable<int> _Company;
		
		private string _ProjectTitle;
		
		private string _Size;
		
		private System.Nullable<System.DateTime> _DateCast;
		
		private System.Nullable<int> _Age;
		
		private System.Nullable<System.DateTime> _DateTest;
		
		private string _Grade;
		
		private System.Nullable<float> _SampleMass;
		
		private System.Nullable<float> _MaxLoad;
		
		private int _CubeID;
		
		public vCubeTestToday()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarCode", DbType="NVarChar(264)")]
		public string BarCode
		{
			get
			{
				return this._BarCode;
			}
			set
			{
				if ((this._BarCode != value))
				{
					this._BarCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpecimenRef", DbType="NVarChar(255)")]
		public string SpecimenRef
		{
			get
			{
				return this._SpecimenRef;
			}
			set
			{
				if ((this._SpecimenRef != value))
				{
					this._SpecimenRef = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobRef", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string JobRef
		{
			get
			{
				return this._JobRef;
			}
			set
			{
				if ((this._JobRef != value))
				{
					this._JobRef = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectCode", DbType="NVarChar(255)")]
		public string ProjectCode
		{
			get
			{
				return this._ProjectCode;
			}
			set
			{
				if ((this._ProjectCode != value))
				{
					this._ProjectCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="Int")]
		public System.Nullable<int> Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this._Company = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectTitle", DbType="NVarChar(255)")]
		public string ProjectTitle
		{
			get
			{
				return this._ProjectTitle;
			}
			set
			{
				if ((this._ProjectTitle != value))
				{
					this._ProjectTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size", DbType="NVarChar(255)")]
		public string Size
		{
			get
			{
				return this._Size;
			}
			set
			{
				if ((this._Size != value))
				{
					this._Size = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCast", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateCast
		{
			get
			{
				return this._DateCast;
			}
			set
			{
				if ((this._DateCast != value))
				{
					this._DateCast = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Int")]
		public System.Nullable<int> Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this._Age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTest", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateTest
		{
			get
			{
				return this._DateTest;
			}
			set
			{
				if ((this._DateTest != value))
				{
					this._DateTest = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grade", DbType="NVarChar(255)")]
		public string Grade
		{
			get
			{
				return this._Grade;
			}
			set
			{
				if ((this._Grade != value))
				{
					this._Grade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SampleMass", DbType="Real")]
		public System.Nullable<float> SampleMass
		{
			get
			{
				return this._SampleMass;
			}
			set
			{
				if ((this._SampleMass != value))
				{
					this._SampleMass = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxLoad", DbType="Real")]
		public System.Nullable<float> MaxLoad
		{
			get
			{
				return this._MaxLoad;
			}
			set
			{
				if ((this._MaxLoad != value))
				{
					this._MaxLoad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CubeID", DbType="Int NOT NULL")]
		public int CubeID
		{
			get
			{
				return this._CubeID;
			}
			set
			{
				if ((this._CubeID != value))
				{
					this._CubeID = value;
				}
			}
		}
	}
	
	public partial class UpdateCubeLoadResult
	{
		
		private int _CubeID;
		
		private System.Nullable<float> _SampleMass;
		
		private System.Nullable<float> _MaxLoad;
		
		public UpdateCubeLoadResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CubeID", DbType="Int NOT NULL")]
		public int CubeID
		{
			get
			{
				return this._CubeID;
			}
			set
			{
				if ((this._CubeID != value))
				{
					this._CubeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SampleMass", DbType="Real")]
		public System.Nullable<float> SampleMass
		{
			get
			{
				return this._SampleMass;
			}
			set
			{
				if ((this._SampleMass != value))
				{
					this._SampleMass = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxLoad", DbType="Real")]
		public System.Nullable<float> MaxLoad
		{
			get
			{
				return this._MaxLoad;
			}
			set
			{
				if ((this._MaxLoad != value))
				{
					this._MaxLoad = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
