#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADM.Data.Object
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ADMDB")]
	public partial class ADMLinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ADMLinqDataContext() : 
				base(global::ADM.Data.Properties.Settings.Default.ADMDBConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public ADMLinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ADMLinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ADMLinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ADMLinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Cube_Detail> Cube_Details
		{
			get
			{
				return this.GetTable<Cube_Detail>();
			}
		}
		
		public System.Data.Linq.Table<Cube_Receiving> Cube_Receivings
		{
			get
			{
				return this.GetTable<Cube_Receiving>();
			}
		}
		
		public System.Data.Linq.Table<vCubeTestAll> vCubeTestAlls
		{
			get
			{
				return this.GetTable<vCubeTestAll>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Cube Details]")]
	public partial class Cube_Detail
	{
		
		private int _ID;
		
		private string _JobRef;
		
		private System.Nullable<int> _Set_No;
		
		private string _SpecimenRef;
		
		private string _Size;
		
		private System.Nullable<System.DateTime> _DateCast;
		
		private System.Nullable<int> _Age;
		
		private System.Nullable<System.DateTime> _DateTest;
		
		private string _Grade;
		
		private System.Nullable<float> _SampleMass;
		
		private System.Nullable<float> _MaxLoad;
		
		public Cube_Detail()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobRef", DbType="NVarChar(255)")]
		public string JobRef
		{
			get
			{
				return this._JobRef;
			}
			set
			{
				if ((this._JobRef != value))
				{
					this._JobRef = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Set No]", Storage="_Set_No", DbType="Int")]
		public System.Nullable<int> Set_No
		{
			get
			{
				return this._Set_No;
			}
			set
			{
				if ((this._Set_No != value))
				{
					this._Set_No = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpecimenRef", DbType="NVarChar(255)")]
		public string SpecimenRef
		{
			get
			{
				return this._SpecimenRef;
			}
			set
			{
				if ((this._SpecimenRef != value))
				{
					this._SpecimenRef = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size", DbType="NVarChar(255)")]
		public string Size
		{
			get
			{
				return this._Size;
			}
			set
			{
				if ((this._Size != value))
				{
					this._Size = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCast", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateCast
		{
			get
			{
				return this._DateCast;
			}
			set
			{
				if ((this._DateCast != value))
				{
					this._DateCast = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Int")]
		public System.Nullable<int> Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this._Age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTest", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateTest
		{
			get
			{
				return this._DateTest;
			}
			set
			{
				if ((this._DateTest != value))
				{
					this._DateTest = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grade", DbType="NVarChar(255)")]
		public string Grade
		{
			get
			{
				return this._Grade;
			}
			set
			{
				if ((this._Grade != value))
				{
					this._Grade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SampleMass", DbType="Real")]
		public System.Nullable<float> SampleMass
		{
			get
			{
				return this._SampleMass;
			}
			set
			{
				if ((this._SampleMass != value))
				{
					this._SampleMass = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxLoad", DbType="Real")]
		public System.Nullable<float> MaxLoad
		{
			get
			{
				return this._MaxLoad;
			}
			set
			{
				if ((this._MaxLoad != value))
				{
					this._MaxLoad = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Cube Receiving]")]
	public partial class Cube_Receiving
	{
		
		private string _JobRef;
		
		private string _ProjectCode;
		
		private System.Nullable<System.DateTime> _DateReceived;
		
		private string _ClientRef;
		
		private string _Casting_Location;
		
		private string _SampleCondition;
		
		private string _TestCondition;
		
		private System.Nullable<int> _TestedBy;
		
		private System.Nullable<int> _PreparedBy;
		
		private System.Nullable<int> _ApprovedBy;
		
		private System.Nullable<System.DateTime> _DateReport;
		
		private string _Remarks;
		
		private string _InvoiceNo;
		
		private string _DateCollection;
		
		private System.Nullable<int> _Field1;
		
		public Cube_Receiving()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobRef", DbType="NVarChar(255)")]
		public string JobRef
		{
			get
			{
				return this._JobRef;
			}
			set
			{
				if ((this._JobRef != value))
				{
					this._JobRef = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectCode", DbType="NVarChar(255)")]
		public string ProjectCode
		{
			get
			{
				return this._ProjectCode;
			}
			set
			{
				if ((this._ProjectCode != value))
				{
					this._ProjectCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateReceived", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateReceived
		{
			get
			{
				return this._DateReceived;
			}
			set
			{
				if ((this._DateReceived != value))
				{
					this._DateReceived = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientRef", DbType="NVarChar(255)")]
		public string ClientRef
		{
			get
			{
				return this._ClientRef;
			}
			set
			{
				if ((this._ClientRef != value))
				{
					this._ClientRef = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Casting Location]", Storage="_Casting_Location", DbType="NVarChar(255)")]
		public string Casting_Location
		{
			get
			{
				return this._Casting_Location;
			}
			set
			{
				if ((this._Casting_Location != value))
				{
					this._Casting_Location = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SampleCondition", DbType="NVarChar(255)")]
		public string SampleCondition
		{
			get
			{
				return this._SampleCondition;
			}
			set
			{
				if ((this._SampleCondition != value))
				{
					this._SampleCondition = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestCondition", DbType="NVarChar(255)")]
		public string TestCondition
		{
			get
			{
				return this._TestCondition;
			}
			set
			{
				if ((this._TestCondition != value))
				{
					this._TestCondition = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestedBy", DbType="Int")]
		public System.Nullable<int> TestedBy
		{
			get
			{
				return this._TestedBy;
			}
			set
			{
				if ((this._TestedBy != value))
				{
					this._TestedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreparedBy", DbType="Int")]
		public System.Nullable<int> PreparedBy
		{
			get
			{
				return this._PreparedBy;
			}
			set
			{
				if ((this._PreparedBy != value))
				{
					this._PreparedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApprovedBy", DbType="Int")]
		public System.Nullable<int> ApprovedBy
		{
			get
			{
				return this._ApprovedBy;
			}
			set
			{
				if ((this._ApprovedBy != value))
				{
					this._ApprovedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateReport", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateReport
		{
			get
			{
				return this._DateReport;
			}
			set
			{
				if ((this._DateReport != value))
				{
					this._DateReport = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="NVarChar(MAX)")]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this._Remarks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNo", DbType="NVarChar(255)")]
		public string InvoiceNo
		{
			get
			{
				return this._InvoiceNo;
			}
			set
			{
				if ((this._InvoiceNo != value))
				{
					this._InvoiceNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCollection", DbType="NVarChar(255)")]
		public string DateCollection
		{
			get
			{
				return this._DateCollection;
			}
			set
			{
				if ((this._DateCollection != value))
				{
					this._DateCollection = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field1", DbType="Int")]
		public System.Nullable<int> Field1
		{
			get
			{
				return this._Field1;
			}
			set
			{
				if ((this._Field1 != value))
				{
					this._Field1 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vCubeTestAll")]
	public partial class vCubeTestAll
	{
		
		private string _BarCode;
		
		private string _SpecimenRef;
		
		private string _JobRef;
		
		private string _ProjectCode;
		
		private string _Company;
		
		private string _ProjectTitle;
		
		private string _Size;
		
		private System.Nullable<System.DateTime> _DateCast;
		
		private System.Nullable<int> _Age;
		
		private System.Nullable<System.DateTime> _DateTest;
		
		private string _Grade;
		
		private System.Nullable<float> _SampleMass;
		
		private System.Nullable<float> _MaxLoad;
		
		private int _ID;
		
		public vCubeTestAll()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarCode", DbType="NVarChar(264)")]
		public string BarCode
		{
			get
			{
				return this._BarCode;
			}
			set
			{
				if ((this._BarCode != value))
				{
					this._BarCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpecimenRef", DbType="NVarChar(255)")]
		public string SpecimenRef
		{
			get
			{
				return this._SpecimenRef;
			}
			set
			{
				if ((this._SpecimenRef != value))
				{
					this._SpecimenRef = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobRef", DbType="NVarChar(255)")]
		public string JobRef
		{
			get
			{
				return this._JobRef;
			}
			set
			{
				if ((this._JobRef != value))
				{
					this._JobRef = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectCode", DbType="NVarChar(255)")]
		public string ProjectCode
		{
			get
			{
				return this._ProjectCode;
			}
			set
			{
				if ((this._ProjectCode != value))
				{
					this._ProjectCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="NVarChar(50)")]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this._Company = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectTitle", DbType="NVarChar(255)")]
		public string ProjectTitle
		{
			get
			{
				return this._ProjectTitle;
			}
			set
			{
				if ((this._ProjectTitle != value))
				{
					this._ProjectTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size", DbType="NVarChar(255)")]
		public string Size
		{
			get
			{
				return this._Size;
			}
			set
			{
				if ((this._Size != value))
				{
					this._Size = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCast", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateCast
		{
			get
			{
				return this._DateCast;
			}
			set
			{
				if ((this._DateCast != value))
				{
					this._DateCast = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Int")]
		public System.Nullable<int> Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this._Age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTest", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateTest
		{
			get
			{
				return this._DateTest;
			}
			set
			{
				if ((this._DateTest != value))
				{
					this._DateTest = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grade", DbType="NVarChar(255)")]
		public string Grade
		{
			get
			{
				return this._Grade;
			}
			set
			{
				if ((this._Grade != value))
				{
					this._Grade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SampleMass", DbType="Real")]
		public System.Nullable<float> SampleMass
		{
			get
			{
				return this._SampleMass;
			}
			set
			{
				if ((this._SampleMass != value))
				{
					this._SampleMass = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxLoad", DbType="Real")]
		public System.Nullable<float> MaxLoad
		{
			get
			{
				return this._MaxLoad;
			}
			set
			{
				if ((this._MaxLoad != value))
				{
					this._MaxLoad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
